apollo:
  client:
    monitor:
      jmx:
        enabled: true
      external:
        type: metheus
  bootstrap:
    namespaces: application,application1
app:
  id: tikview
logging:
  level:
    com.ctrip.framework.apollo: debug
