server:
  port: 8080
apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
  config-service: http://81.68.181.139:8080
spring:
  profiles:
    active: jmx-prometheus-500-error-namespace